---
image: docker:19.03.1

services:
  - docker:19.03.1-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

push-tag:
  stage: deploy
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker tag $CI_REGISTRY_IMAGE $DOCKER_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $DOCKER_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  except:
    refs:
      - main

push-latest:
  stage: deploy
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker tag $CI_REGISTRY_IMAGE $DOCKER_REGISTRY/$CI_REGISTRY_IMAGE:latest
    - docker push $DOCKER_REGISTRY/$CI_REGISTRY_IMAGE:latest
  only:
    refs:
      - main
